export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function ProjectLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>; // ✅ No <html> or <body>
}
